spring:
  application:
    name: spring-grpc-server
  grpc:
    server:
      port: 9090

  data:
    mongodb:
      uri: mongodb+srv://${mongodb.username}:${mongodb.password}@${mongodb.host}/?retryWrites=true&w=majority&appName=Gipter-test
      database: ${mongodb.database}

server:
  port: 8080

management:
  endpoints:
    access:
      default: read_only
    web:
      exposure:
        include: health,info,beans
      base-path: /status